# 안녕하세요
## 안녕하세요
### 안녕하세요
* 안녕하세요
- 안녕하세요

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

## Data

- we will use fake data for this example

In [3]:
torch.manual_seed(1)

In [5]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

In [10]:
print(x_train)
print(x_train.shape)
print(x_train.size())

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
torch.Size([3, 1])


### Weight Initialization

In [11]:
W=torch.zeros(1,requires_grad=True) #미분이 가능한 1나의차원 0 생성
print(W)

tensor([0.], requires_grad=True)


In [12]:
b=torch.zeros(1,requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


### Hypothesis

In [15]:
hypothesis=x_train*W*b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<MulBackward0>)


### Cost

In [16]:
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<MulBackward0>)


In [17]:
print(y_train)

tensor([[1.],
        [2.],
        [3.]])


In [18]:
print(hypothesis-y_train)

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [20]:
print((hypothesis-y_train)**2)

tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)


In [24]:
cost=torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


In [26]:
optimizer=optim.SGD([W,b],lr=0.01)

## Full Code

In [37]:
#데이터
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

#모델 초기화
W=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b],lr=0.01)

nb_epochs=1000
for epoch in range(nb_epochs+1):
    
    #H(w)계산
    hypothesis=x_train*W+b
    
    #cost 계산
    cost=torch.mean((hypothesis-y_train)**2)
    
    #cost로 H(w)개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #100번마다 로그 출력
    if epoch %100==0:
        print('Epoch {:4d}/{}  W: {:.3f},  b:{:.3f}   Cost:{:.6f}'.format(
        epoch,nb_epochs,W.item(),b.item(),cost.item()
        ))
                    

Epoch    0/1000  W: 0.093,  b:0.040   Cost:4.666667
Epoch  100/1000  W: 0.873,  b:0.289   Cost:0.012043
Epoch  200/1000  W: 0.900,  b:0.227   Cost:0.007442
Epoch  300/1000  W: 0.921,  b:0.179   Cost:0.004598
Epoch  400/1000  W: 0.938,  b:0.140   Cost:0.002842
Epoch  500/1000  W: 0.951,  b:0.110   Cost:0.001756
Epoch  600/1000  W: 0.962,  b:0.087   Cost:0.001085
Epoch  700/1000  W: 0.970,  b:0.068   Cost:0.000670
Epoch  800/1000  W: 0.976,  b:0.054   Cost:0.000414
Epoch  900/1000  W: 0.981,  b:0.042   Cost:0.000256
Epoch 1000/1000  W: 0.985,  b:0.033   Cost:0.000158


## High-level Implementation with nn.module

In [50]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)


In [63]:
#데이터
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

#모델 초기화
model=LinearRegressionModel()

optimizer=optim.SGD(model.parameters(),lr=0.01)

nb_epochs=1000
for epoch in range(nb_epochs+1):
    
    #H(w)계산
    prediction=model(x_train)
    
    #cost 계산
    cost=F.mse_loss(prediction,y_train)
    
    #cost로 H(w)개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #100번마다 로그 출력
    if epoch %100==0:
        params=list(model.parameters())
        W=params[0].item()
        b=params[1].item()
        
        print('Epoch {:4d}/{}  W: {:.3f},  b:{:.3f}   Cost:{:.6f}'.format(
        epoch,nb_epochs,W,b,cost.item()
        ))
            

Epoch    0/1000  W: 0.896,  b:-0.158   Cost:0.178288
Epoch  100/1000  W: 1.033,  b:-0.074   Cost:0.000794
Epoch  200/1000  W: 1.026,  b:-0.058   Cost:0.000491
Epoch  300/1000  W: 1.020,  b:-0.046   Cost:0.000303
Epoch  400/1000  W: 1.016,  b:-0.036   Cost:0.000187
Epoch  500/1000  W: 1.012,  b:-0.028   Cost:0.000116
Epoch  600/1000  W: 1.010,  b:-0.022   Cost:0.000072
Epoch  700/1000  W: 1.008,  b:-0.018   Cost:0.000044
Epoch  800/1000  W: 1.006,  b:-0.014   Cost:0.000027
Epoch  900/1000  W: 1.005,  b:-0.011   Cost:0.000017
Epoch 1000/1000  W: 1.004,  b:-0.009   Cost:0.000010
