In [4]:
import numpy as np
import torch
t=np.array([1,2,3,4,5,6])
print(t)

[1 2 3 4 5 6]


In [6]:
print("Rank of t : ",t.ndim)
print("Shape of t:",t.shape)

Rank of t :  1
Shape of t: (6,)


In [10]:
print("t[0], t[1], t[-1]= ",t[0],t[1],t[-1])
print("t[2:5]","t[4:-1]=",t[2:5],t[4:-1])

t[0], t[1], t[-1]=  1 2 6
t[2:5] t[4:-1]= [3 4 5] [5]


In [12]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [16]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)


Rank  of t:  2
Shape of t:  (4, 3)


In [19]:
m1=torch.FloatTensor([[3,3]])

In [20]:
m2=torch.FloatTensor([[2,2]])

In [21]:
print(m1+m2)

tensor([[5., 5.]])


In [22]:
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [23]:
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [24]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [27]:
print()
print('----------')
print('Mul vs Matmul')
print('----------')
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])

print(m1.matmul(m2))


----------
Mul vs Matmul
----------
tensor([[ 5.],
        [11.]])


In [28]:
print()
print('----------')
print('Mul vs Matmul')
print('----------')
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])

print(m1*m2)


----------
Mul vs Matmul
----------
tensor([[1., 2.],
        [6., 8.]])


In [29]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [35]:
t=torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [36]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [38]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [39]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [42]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))#마지막 차원에서 즉 2차원이나(0-1)

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [43]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [44]:
print(t.max())

tensor(4.)


In [45]:
print(t.max(dim=0))
print('Max : ',t.max(dim=0)[0])
print('Arg : ',t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max :  tensor([3., 4.])
Arg :  tensor([1, 1])


In [46]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [48]:
t=np.array([[[0,1,2],
           [3,4,5]],
          
          [[6,7,8],
          [9,10,11]]])
ft=torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [53]:
print(ft.view([-1,6]))
print(ft.view([-1,2]).shape)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
torch.Size([6, 2])


In [50]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
